### PR TITLE
Move the freeRADIUS exporter installation to the base image and pass base image as arg to the main Dockerfile

### PR DESCRIPTION
**Pull request by robinmitra**

### CODE REVIEW

**Review by sarahseewhy — APPROVED** [review]
LGTM.

We will push these changes to staging and try restarting the containers.

**Comment by sarahseewhy** [comment]
We've parked this work for the moment. For updates see [this trello card](https://trello.com/c/xR6hH1dL/174-separate-the-dockerfiles-for-frontend-freeradius-and-health-checks-ruby-more-doc-handover-from-robin).

**Comment by szd55gds** [comment]
@dependabot-bot recreate

**Comment by szd55gds** [comment]
@dependabot recreate

**Pull request closed without merging**
